name: APCSP_Create
description: AP Computer Science Principles Create Project
# version: 1.0.0
# author: Admin <lockedthreaddev@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  args: ^1.5.2
  http: ^0.12.0+4